### ISSUE TITLE
Distinguishing between the copyright years for existing and new files

### ISSUE THREAD

**Issue by zhongzc** [korandoru/hawkeye#111]
As a new year begins, updating copyrights is a task that developers find a bit exciting. In simple terms, my understanding is that the year in existing code files can stay as is, while files created in the new year should reflect that year's date. Yet, when following this practice, I didn’t pass the GitHub action check with `korandoru/hawkeye`.

Could you please clarify if there’s a mistake in my grasp of licensing, or if I've overlooked how to properly set up the checker?

Project: https://github.com/GreptimeTeam/greptimedb

**Comment by tisonkun** [comment]
If you're using Apache License, the year in license header can be pinned to the interception year. This is shown in our README.

Also, you can take a look at the following discussion for more background:

* https://issues.apache.org/jira/browse/LEGAL-629
* https://github.com/apache/skywalking/issues/10223

So, GreptimeDB was established in 2022; using 2022 everywhere complies with the license policy.

Technically, we can make some plugin to provide extra properties to use, like file created year. I don't find they're useful before so it's removed at [this commit](https://github.com/korandoru/hawkeye/commit/d69b1d427e226bc4cc4f2a26c6a29174a768abee#diff-97ee8538c2229098cf6d96b7da1d5608f7d4b6857aec8f6696cd6a492069b5c2L83-L89). But it's technically possible.

**Comment by zhongzc** [comment]
Thanks for the answer
