### ISSUE TITLE
`hawkeye.core.filename` Property Not Working

### ISSUE THREAD

**Issue by yushan87** [korandoru/hawkeye#113]
According to the documentation, `hawkeye.core.filename` should have the name of the file. However, it is not there if you try to use it in your header template file. 

### My header template file is as follows:
```
${hawkeye.core.filename}
------------------------------------------
Copyright (c) ${year}
${owner}
------------------------------------------
```

### Expected Resulting File (with `year = 2024` and `owner = "Some_Name"`:
```
/*
 * my_file.c
 * ------------------------------------------
 * Copyright (c) 2024
 * Some_Name
 * ------------------------------------------
 */
```

### Actual Resulting File (with `year = 2024` and `owner = "Some_Name"`:
```
/*
 * ${hawkeye.core.filename}
 * ------------------------------------------
 * Copyright (c) 2024
 * Some_Name
 * ------------------------------------------
 */
```

**Comment by tisonkun** [comment]
@yushan87 I add a test case fb65030307cfd210a8fc1dfb0a84f2653efe34a3 and it seems that this issue is invalid.

But I rename the property name starting from 4.0.0 so if you are using a former version, you may observe this manner.

**Comment by yushan87** [comment]
Thank you for looking into it! One difference I am noticing is that I provided a header template file rather than using an inline header like you have. Would you be willing to add a test for that as well?

**Comment by tisonkun** [comment]
Added.
