### ISSUE TITLE
Fails to build with Rust stable

### ISSUE THREAD

**Issue by orhun** [korandoru/hawkeye#130]
Hello! 👋🏼 

I [packaged](https://archlinux.org/packages/extra/x86_64/hawkeye/) this tool for Arch Linux, however I'm hitting:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> fmt/src/lib.rs:15:1
   |
15 | #![feature(extract_if)]
   | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> fmt/src/lib.rs:16:1
   |
16 | #![feature(let_chains)]
   | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> fmt/src/lib.rs:15:12
   |
15 | #![feature(extract_if)]
   |            ^^^^^^^^^^
```

I solved this by using `cargo-nightly` package but this unfortunately effects reproducibility :/

I was wondering if it is possible to support Rust stable 👀

**Comment by tisonkun** [comment]
It should be possible.

These functions are not quite complex, but they made the code tidier. If you want to use it with stable, you can expand let-chains and write a handmade extract_if or inline the functionality.

Since we can use it as a compiled binary and a docker image now, I don't find it a blocker for general usage >_<

**Comment by tisonkun** [comment]
> I solved this by using cargo-nightly package but this unfortunately effects reproducibility 

Interesting.

If you build with the source of the repo, these lines would pin the toolchain:

https://github.com/korandoru/hawkeye/blob/584dad0bdb28f3258a96c92f7c5512a9d0030891/rust-toolchain.toml#L15-L17

No matter which "bootstrap toolchain" in use.

**Comment by orhun** [comment]
> IIUC the rust-toolchain.toml file should make the build reproducible.

Oops, yeah. I think it should be fine.

> These functions are not quite complex, but they made the code tidier. If you want to use it with stable

Would you be interested in a PR to remove those nightly usages and make it possible to build with stable anyways? If not, it's fine 🐻

**Comment by tisonkun** [comment]
> Would you be interested in a PR to remove those nightly usages and make it possible to build with stable anyways?

Yes. As stated above, I'm open to such changes (will merge if it's well implemented). But I don't have motivation to do it myself :D
