### ISSUE TITLE
error: unexpected argument '' found

### ISSUE THREAD

**Issue by Xuanwo** [korandoru/hawkeye#145]
I'm not sure if this error related to the newest 5.5 release.

https://github.com/apache/opendal/actions/runs/8811377579/job/24185252046

![image](https://github.com/korandoru/hawkeye/assets/5351546/dab4c858-a98e-4840-ba1a-9aaac2941d4d)

**Comment by tisonkun** [comment]
This is resolved by https://github.com/korandoru/hawkeye/pull/146.
