### ISSUE TITLE
Support for different years

### ISSUE THREAD

**Issue by hnorkowski** [korandoru/hawkeye#147]
Is there a way to allow different years in the license header? E.g. in a project that is developed over multiple years and some file are not touched, the year could be different to new files.

**Comment by tisonkun** [comment]
I support you need something like `${git.fileAddedYear}` to be inserted in the template?

**Comment by tisonkun** [comment]
This can be related to https://github.com/korandoru/hawkeye/issues/114. I can try to build it when `git` present.

We depend on `git` because the file created year is inaccurate from the FS's stats that would be the physical created date (i.e., when you clone the repo and get the file).
