### ISSUE TITLE
Evaluate SubstrateVM base image

### ISSUE THREAD

**Issue by tisonkun** [korandoru/hawkeye#17]
Background: https://github.com/chainguard-images/images/issues/171

Actually, there's a dirty commit including the necessary change https://github.com/korandoru/hawkeye/commit/dbd535365cd9e82978f3defadcf1c745e0ca37ac.

But I wonder whether we can rely on it stably and whether it works correctly on multiple arches or different environments. So further research is needed.

cc @dlorenc

**Comment by dlorenc** [comment]
We've pushed it to a stable location at `cgr.dev/chainguard/graalvm-native-image-base` !

**Comment by tisonkun** [comment]
@dlorenc Does `cgr.dev/chainguard/graalvm-native-image-base` have both arch support for arm64 and amd64 adaptive?

**Comment by imjasonh** [comment]
> And where can I browser the image metadata?

You can browse image metadata at https://registry-ui.chainguard.app/?image=cgr.dev/chainguard/graalvm-native-image-base

You can also use [`cosign`](https://docs.sigstore.dev/cosign/overview/) to browse SBOM and attestation data, e.g.:

```
cosign download sbom cgr.dev/chainguard/graalvm-native-image-base --platform=linux/amd64
```

**Comment by tisonkun** [comment]
Closed. I'm going to release the first version using graalvm-native-image-base in days.

One comment I just noticed: since `graalvm-native-image-base` is experimental, I can use only the `latest` tag now. Is there an estimate to release a stable or reliable fixed tag? Is there anything I can help (to verify)?

**Comment by dlorenc** [comment]
I sent this to remove experimental:

https://github.com/chainguard-images/images/pull/202

If you could just plus one that and say this works it would help :)
