### ISSUE TITLE
Support pluggable Git integration

### ISSUE THREAD

**Issue by tisonkun** [korandoru/hawkeye#20]
license-maven-plugin has a pluggable Git integration [license-maven-plugin-git](https://github.com/mathieucarbou/license-maven-plugin/tree/master/license-maven-plugin-git).

We can have a similar plugin to populate Git-related information like first commit time, last commit time and excludes from `.gitignore` rules, etc.

It will require a plugin strategy and perhaps dynamically loaded. But in the native image and command line fat jar, we may bundle them. I'm unsure now.

For Git interoperation library, jgit is a good choice: https://www.eclipse.org/jgit/

**Comment by spencercjh** [comment]
More details:

[license-maven-plugin-git](https://github.com/mathieucarbou/license-maven-plugin/tree/master/license-maven-plugin-git) is a jar which will be added to [the dependencies of the plugin](https://github.com/mathieucarbou/license-maven-plugin/blob/ee97a27c0fdf439ac3f8bbf281497572708c65da/license-maven-plugin-fs/README.md#how-to-use-license-maven-plugin-fs).

```xml
<plugin>
    <groupId>com.mycila</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <version>${license-maven-plugin.version}</version>
    <configuration>
      <header>my-header-folder/my-header-template.txt</header>
     ...
    </configuration>
    <dependencies>
      <dependency>
        <groupId>com.mycila</groupId>
        <artifactId>license-maven-plugin-fs</artifactId>
        <!-- make sure you use the same version as license-maven-plugin -->
        <version>${license-maven-plugin.version}</version>
      </dependency>
    </dependencies>
    <executions>
      ...
    </executions>
</plugin>
```

It implements the interface `PropertiesProvider` and will be loaded [here](https://github.com/mathieucarbou/license-maven-plugin/blob/d22d27d024861d485b0fee1da7c29f0a5a634dcc/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java#L637)

```java
for (final PropertiesProvider provider : ServiceLoader.load(PropertiesProvider.class,
    Thread.currentThread().getContextClassLoader())) {
  provider.init(this, globalProperties);
  propertiesProviders.add(provider);
}
```

**Comment by tisonkun** [comment]
Yes. Another important improvement is filtering out files that ignored by `.gitignore` file.
