### ISSUE TITLE
Distribute as a Maven plugin

### ISSUE THREAD

**Issue by tisonkun** [korandoru/hawkeye#21]
So, this project is strongly inspired by [license-maven-plugin](https://github.com/mathieucarbou/license-maven-plugin), with an initial motivation to bring it beyond a Maven plugin.

But, with a core library to support basic check, format, and remove logic, we can evaluate building a maven plugin upon these core functions :)

The significant part is that we should populate properties correctly and do the right overriding. Also, the license-maven-plugin supports a few "multi" configs, while I'd prefer to use multiple executions simply. But this should also be verified.

**Comment by spencercjh** [comment]
I will try to do it.

**Comment by spencercjh** [comment]
> @spencercjh Glad to see you!
> 
> Most of the knowledge for packaging a Maven plugin, you can learn from the license-maven-plugin as linked above. Let me know if you need any help and it's encourage to submit a draft PR once you make any progress so we can talk on the same page.

Thanks for your reply.

It's my first to creating Maven plugin. And I create a simple Maven plugin sample [here](https://github.com/spencercjh/hawkeye/commit/e6d314f913eb2e123aed53e344cc10b59ff30211).

I want to know if this issue is aimed at migrating the work of `hawkeye-command` to `hawkeye-maven-plugin`.

**Comment by spencercjh** [comment]
I'm unsure how the style of Java is standardized for big organizations because `Hawkeye` is my first Java OSS to be involved. I found that Your import package order is not the same as mine. It's not relevant to the issue but directly related to my contribution.

**Comment by tisonkun** [comment]
@spencercjh For this kind of style mismatch, you can fix by:

```
./mvnw spotless:apply
```

... and to apply license headers for all the new files (exactly what this repository want to do), you can refer to the README and fix it up. For example,

```
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye-native:v3 format
```

... or test out your local version of HawkEye.
