### ISSUE TITLE
Factor out the reporting logics

### ISSUE THREAD

**Issue by tisonkun** [korandoru/hawkeye#86]
Now we always print the result to the console in a fixed format.

We should build an internal report data structure and adapt it to multiple reporting format (HTML, XML, console plain text, etc.).

**Comment by dshunter107** [comment]
Hello. 
I am interested in working on this issue; however, I am rather new to GitHub and development. I have taken several computer science classes (including data structures and algorithms), and I have built some programs in the past. I am also familiar with GitHub commits, push, and pull requests. Can you tell me more about this issue. What type of data structure would you be looking for, and where would be a good place to look in the program to start working on this issue?

**Comment by tisonkun** [comment]
@dshunter107 Glad to see you :D

The data structure should be relatively simple:

```
Filepath -> License check result (present / missing / noop / added / replaced / removed / unknown)
```

You can take a look at the `ReportConstants` class where I use a flatten and String-represent solution for now.

For the report format, you can take a look at Maven's Report Mojo designs:

* https://maven.apache.org/guides/plugin/guide-java-report-plugin-development.html
* https://maven.apache.org/plugins/maven-site-plugin/examples/configuring-reports.html

**Comment by tisonkun** [comment]
No longer relvant.
